name: ap_matrimony
description: "AP Matrimony - A fully functional frontend-only Matrimony Platform in Flutter."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  go_router: ^14.8.1
  fl_chart: ^0.69.2
  google_fonts: ^6.2.1
  intl: ^0.20.2
  percent_indicator: ^4.2.3
  shared_preferences: ^2.3.3
  pdf: ^3.11.3
  printing: ^5.14.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  image_path: "assets/icon/app_icon.png"
  
  # Android specific configurations  
  android:
    generate: true
    image_path: "assets/icon/app_icon.png"
    adaptive_icon_background: "#FFFFFF"
    adaptive_icon_foreground: "assets/icon/app_icon.png"
  
  # iOS specific configurations
  ios:
    generate: true
    image_path: "assets/icon/app_icon.png"
    
  # Web specific configurations
  web:
    generate: true
    image_path: "assets/icon/app_icon.png"
    background_color: "#FFFFFF"
    theme_color: "#0175C2"

flutter:
  uses-material-design: true
  generate: true
  
  # Assets
  assets:
    - assets/images/
    - assets/images/profiles/
    - assets/images/success_stories/
    - assets/icon/
